services:
  devcontainer:
    image: node:18-bookworm
    command: /bin/bash -c "npm i && npm run docker"
    working_dir: /workspace
    container_name: devcontainer
    init: true
    ports:
      # ***************************************************
      # DO NOT REMOVE THE MAPPER FOR LOCALHOST (127.0.0.1)
      # IF YOU DO IT YOU MIGHT GET HACKED
      # ***************************************************
      - '127.0.0.1:5173:5173'
    volumes:
      - .:/workspace:cached
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
